/*
 * SPDX-License-Identifier: MIT
 *
 * Maps INPUT_VIRTUAL_SYM_* codes (0x100–0x13D) to LV_SYMBOL_* string pointers.
 * Indexed by (code - 0x100); entries outside range return LV_SYMBOL_DUMMY.
 */

#pragma once

#include <lvgl.h>
#include <dt-bindings/xiaord/input_codes.h>

#define SYM_BASE 0x100
#define SYM_MAX  0x13D

static const char *const s_sym_table[] = {
	[INPUT_VIRTUAL_SYM_BULLET        - SYM_BASE] = LV_SYMBOL_BULLET,
	[INPUT_VIRTUAL_SYM_AUDIO         - SYM_BASE] = LV_SYMBOL_AUDIO,
	[INPUT_VIRTUAL_SYM_VIDEO         - SYM_BASE] = LV_SYMBOL_VIDEO,
	[INPUT_VIRTUAL_SYM_LIST          - SYM_BASE] = LV_SYMBOL_LIST,
	[INPUT_VIRTUAL_SYM_OK            - SYM_BASE] = LV_SYMBOL_OK,
	[INPUT_VIRTUAL_SYM_CLOSE         - SYM_BASE] = LV_SYMBOL_CLOSE,
	[INPUT_VIRTUAL_SYM_POWER         - SYM_BASE] = LV_SYMBOL_POWER,
	[INPUT_VIRTUAL_SYM_SETTINGS      - SYM_BASE] = LV_SYMBOL_SETTINGS,
	[INPUT_VIRTUAL_SYM_HOME          - SYM_BASE] = LV_SYMBOL_HOME,
	[INPUT_VIRTUAL_SYM_DOWNLOAD      - SYM_BASE] = LV_SYMBOL_DOWNLOAD,
	[INPUT_VIRTUAL_SYM_DRIVE         - SYM_BASE] = LV_SYMBOL_DRIVE,
	[INPUT_VIRTUAL_SYM_REFRESH       - SYM_BASE] = LV_SYMBOL_REFRESH,
	[INPUT_VIRTUAL_SYM_MUTE          - SYM_BASE] = LV_SYMBOL_MUTE,
	[INPUT_VIRTUAL_SYM_VOLUME_MID    - SYM_BASE] = LV_SYMBOL_VOLUME_MID,
	[INPUT_VIRTUAL_SYM_VOLUME_MAX    - SYM_BASE] = LV_SYMBOL_VOLUME_MAX,
	[INPUT_VIRTUAL_SYM_IMAGE         - SYM_BASE] = LV_SYMBOL_IMAGE,
	[INPUT_VIRTUAL_SYM_TINT          - SYM_BASE] = LV_SYMBOL_TINT,
	[INPUT_VIRTUAL_SYM_PREV          - SYM_BASE] = LV_SYMBOL_PREV,
	[INPUT_VIRTUAL_SYM_PLAY          - SYM_BASE] = LV_SYMBOL_PLAY,
	[INPUT_VIRTUAL_SYM_PAUSE         - SYM_BASE] = LV_SYMBOL_PAUSE,
	[INPUT_VIRTUAL_SYM_STOP          - SYM_BASE] = LV_SYMBOL_STOP,
	[INPUT_VIRTUAL_SYM_NEXT          - SYM_BASE] = LV_SYMBOL_NEXT,
	[INPUT_VIRTUAL_SYM_EJECT         - SYM_BASE] = LV_SYMBOL_EJECT,
	[INPUT_VIRTUAL_SYM_LEFT          - SYM_BASE] = LV_SYMBOL_LEFT,
	[INPUT_VIRTUAL_SYM_RIGHT         - SYM_BASE] = LV_SYMBOL_RIGHT,
	[INPUT_VIRTUAL_SYM_PLUS          - SYM_BASE] = LV_SYMBOL_PLUS,
	[INPUT_VIRTUAL_SYM_MINUS         - SYM_BASE] = LV_SYMBOL_MINUS,
	[INPUT_VIRTUAL_SYM_EYE_OPEN      - SYM_BASE] = LV_SYMBOL_EYE_OPEN,
	[INPUT_VIRTUAL_SYM_EYE_CLOSE     - SYM_BASE] = LV_SYMBOL_EYE_CLOSE,
	[INPUT_VIRTUAL_SYM_WARNING       - SYM_BASE] = LV_SYMBOL_WARNING,
	[INPUT_VIRTUAL_SYM_SHUFFLE       - SYM_BASE] = LV_SYMBOL_SHUFFLE,
	[INPUT_VIRTUAL_SYM_UP            - SYM_BASE] = LV_SYMBOL_UP,
	[INPUT_VIRTUAL_SYM_DOWN          - SYM_BASE] = LV_SYMBOL_DOWN,
	[INPUT_VIRTUAL_SYM_LOOP          - SYM_BASE] = LV_SYMBOL_LOOP,
	[INPUT_VIRTUAL_SYM_DIRECTORY     - SYM_BASE] = LV_SYMBOL_DIRECTORY,
	[INPUT_VIRTUAL_SYM_UPLOAD        - SYM_BASE] = LV_SYMBOL_UPLOAD,
	[INPUT_VIRTUAL_SYM_CALL          - SYM_BASE] = LV_SYMBOL_CALL,
	[INPUT_VIRTUAL_SYM_CUT           - SYM_BASE] = LV_SYMBOL_CUT,
	[INPUT_VIRTUAL_SYM_COPY          - SYM_BASE] = LV_SYMBOL_COPY,
	[INPUT_VIRTUAL_SYM_SAVE          - SYM_BASE] = LV_SYMBOL_SAVE,
	[INPUT_VIRTUAL_SYM_BARS          - SYM_BASE] = LV_SYMBOL_BARS,
	[INPUT_VIRTUAL_SYM_ENVELOPE      - SYM_BASE] = LV_SYMBOL_ENVELOPE,
	[INPUT_VIRTUAL_SYM_CHARGE        - SYM_BASE] = LV_SYMBOL_CHARGE,
	[INPUT_VIRTUAL_SYM_PASTE         - SYM_BASE] = LV_SYMBOL_PASTE,
	[INPUT_VIRTUAL_SYM_BELL          - SYM_BASE] = LV_SYMBOL_BELL,
	[INPUT_VIRTUAL_SYM_KEYBOARD      - SYM_BASE] = LV_SYMBOL_KEYBOARD,
	[INPUT_VIRTUAL_SYM_GPS           - SYM_BASE] = LV_SYMBOL_GPS,
	[INPUT_VIRTUAL_SYM_FILE          - SYM_BASE] = LV_SYMBOL_FILE,
	[INPUT_VIRTUAL_SYM_WIFI          - SYM_BASE] = LV_SYMBOL_WIFI,
	[INPUT_VIRTUAL_SYM_BATTERY_FULL  - SYM_BASE] = LV_SYMBOL_BATTERY_FULL,
	[INPUT_VIRTUAL_SYM_BATTERY_3     - SYM_BASE] = LV_SYMBOL_BATTERY_3,
	[INPUT_VIRTUAL_SYM_BATTERY_2     - SYM_BASE] = LV_SYMBOL_BATTERY_2,
	[INPUT_VIRTUAL_SYM_BATTERY_1     - SYM_BASE] = LV_SYMBOL_BATTERY_1,
	[INPUT_VIRTUAL_SYM_BATTERY_EMPTY - SYM_BASE] = LV_SYMBOL_BATTERY_EMPTY,
	[INPUT_VIRTUAL_SYM_USB           - SYM_BASE] = LV_SYMBOL_USB,
	[INPUT_VIRTUAL_SYM_BLUETOOTH     - SYM_BASE] = LV_SYMBOL_BLUETOOTH,
	[INPUT_VIRTUAL_SYM_TRASH         - SYM_BASE] = LV_SYMBOL_TRASH,
	[INPUT_VIRTUAL_SYM_BACKSPACE     - SYM_BASE] = LV_SYMBOL_BACKSPACE,
	[INPUT_VIRTUAL_SYM_SD_CARD       - SYM_BASE] = LV_SYMBOL_SD_CARD,
	[INPUT_VIRTUAL_SYM_NEW_LINE      - SYM_BASE] = LV_SYMBOL_NEW_LINE,
	[INPUT_VIRTUAL_SYM_DUMMY         - SYM_BASE] = LV_SYMBOL_DUMMY,
	[INPUT_VIRTUAL_SYM_EDIT          - SYM_BASE] = LV_SYMBOL_EDIT,
};

static inline const char *sym_code_to_str(uint16_t code)
{
	uint16_t idx = code - SYM_BASE;

	if (idx >= ARRAY_SIZE(s_sym_table) || s_sym_table[idx] == NULL) {
		return LV_SYMBOL_DUMMY;
	}
	return s_sym_table[idx];
}
